language: ruby

rvm:
  - 2.3.1

branches:
  only:
    - master

before_script:
  - mysql -e 'create database tippspiel_test;'
  - cp config/database.yml.travis config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake

bundler_args: "--without development production"

env:
  global:
    - WEBSITE_URL='http://localhost:3000'
    - ADMIN_EMAIL='test-tippspiel@test.com'
    - MAIL='tippspiel@test.com'
    - SECRET_BASE_KEY='r90435943jv90t960dc87966cdfe8a6b730c1ecbee871d6a4b92e4687b34cb29d99f67981a8ca5522671db884aec9d1d0c296f1660bce_travis'
    - COOKIE_STORE_KEY='_tavis_tippspiel_session'

addons:
    code_climate:
        repo_token: 5d39b53f326f9338702e692265bc1e56a350fde3f866f05a37db78c49789aceb